config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users

  # get '/pokemons', to: 'pokemons#index'
  # get '/pokemons/:id', to: 'pokemons#show'

  root 'overview#index'

  resources :pokemons
  resources :users

  get '/overview', to: 'overview#index'

  # user_pokemons
  get '/my-pokemons', to: 'users#my_pokemons'
  post '/add-pokemon', to: 'users#add_pokemon'
  post '/remove-pokemon', to: 'users#remove_pokemon'
  get '/caught_pokemon', to: 'users#caught_pokemon'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
# frozen_string_literal: true

class Pokemon < ApplicationRecord
  enum element_type: {
    Normal: 0,
    Fire: 1,
    Water: 2,
    Grass: 3,
    Electric: 4,
    Ice: 5,
    Fighting: 6,
    Poison: 7,
    Ground: 8,
    Flying: 9,
    Psychic: 10,
    Bug: 11,
    Rock: 12,
    Ghost: 13,
    Dragon: 14,
    Dark: 15,
    Steel: 16,
    Fairy: 17
  }

  has_many :user_pokemons
  has_many :users, through: :user_pokemons
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { admin: 0, trainer: 1 }

  has_many :user_pokemons
  has_many :pokemons, through: :user_pokemons

  def recent_pokemons
    pokemons.where('user_pokemons.created_at > ?', Time.now - 7.days)
  end

  def remove_pokemon(id:)
    user_pokemons.where(pokemon_id: id).first.destroy
  end

  def add_pokemon(new_pokemon_id:)
    UserPokemon.create(user_id: id, pokemon_id: new_pokemon_id)
  end

  def caught_last_seven_days?
    last_caught_pokemon = user_pokemons.last
    return false if last_caught_pokemon.nil?

    Time.now - 7.days < last_caught_pokemon.created_at
  end
end

app/models/user_pokemon.rb
# frozen_string_literal: true

class UserPokemon < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit::Authorization

  # handle redirect with devise gem
  def after_sign_in_path_for(_resource)
    root_path
  end
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  layout 'sidebar'
  def index; end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  layout 'sidebar'
  before_action :find_by_id, only: %i[show edit update destroy]

  def index
    @pokemons = if params[:search].present?
                  Pokemon.where('lower(name) LIKE ?',
                                "%#{params[:search].downcase}%").order(params[:sort])
                else
                  Pokemon.all.order(params[:sort])
                end
    authorize @pokemons
  end

  def show; end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    authorize @pokemon
    if @pokemon.save
      redirect_to @pokemon
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    authorize @pokemon
    if @pokemon.update(pokemon_params)
      redirect_to @pokemon
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @pokemon
    @pokemon.destroy

    redirect_to pokemons_path, status: :see_other
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :image, :main_technique, :element_type, :description)
  end

  def find_by_id
    @pokemon = Pokemon.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'sidebar'
  before_action :find_by_id, only: %i[show edit update destroy]

  def index
    @users = if params[:search].present?
               User.where('lower(name) LIKE ?',
                          "%#{params[:search].downcase}%").order(params[:sort]).paginate(page: params[:page], per_page: 10)
             else
               User.all.order(params[:sort]).paginate(page: params[:page], per_page: 10)
             end
    authorize @users
  end

  def show
    @user_pokemons = @user.pokemons
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    authorize @user
    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @user
    @user.destroy

    redirect_to users_path, status: :see_other
  end

  def my_pokemons; end

  def caught_pokemon
    @pokemons = Pokemon.all
  end

  def remove_pokemon
    current_user.remove_pokemon(id: params[:pokemon_id])

    redirect_to my_pokemons_path, status: :see_other
  end

  def add_pokemon
    current_user.add_pokemon(new_pokemon_id: params[:pokemon_id])

    redirect_to my_pokemons_path, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def find_by_id
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sidebar_helper.rb
module SidebarHelper
  def current_class_by(path:)
    'active' if request.path == path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<header
  class="bg-white border-b border-gray-300 flex justify-between p-4 sticky top-0 h-20 z-10 items-center"
>
  <div class="px-6">Pokedex</div>
  <div>
    <%= button_to "logout", destroy_user_session_path, method: :delete%>
  </div>
  <div class="md:hidden">☰</div>
</header>

app/views/application/_navbar.html.erb
<%= stylesheet_link_tag 'sidebar' %>

<nav
  class="bg-white border-r border-gray-300 w-1/5 md:flex flex-col hidden justify-between p-4 text-center sticky top-20 h-[calc(100vh-80px)]"
>
  <div>
    <div class="nav-item">
      <%= link_to(root_path, class: "nav-link p-6 flex text-gray-600 hover:text-purple-600 truncate #{current_class_by(path: root_path)}") do %>
        <%= heroicon "eye", options: { class: "h-5 w-5 text-purple-800" } %>
        <span class="px-1">Overview</span>
      <% end %>
    </div>
    <div class="nav-item ">
      <%= link_to(my_pokemons_path, class: "nav-link p-6 flex text-gray-600 hover:text-purple-600 truncate #{current_class_by(path: my_pokemons_path)}") do %>
        <%= heroicon "chat-bubble-bottom-center", options: { class: "h-5 w-5 text-purple-800" } %>
        <span class="px-1">My Caught</span>
      <% end %>
    </div>
    <div class="nav-item">
      <%= link_to(pokemons_path, class: "nav-link p-6 flex text-gray-600 hover:text-purple-600 truncate #{current_class_by(path: pokemons_path)}") do %>
        <%= heroicon "chat-bubble-left-right", options: { class: "h-5 w-5 text-purple-800" } %>
        <span class="px-1">Pokemons</span>
      <% end %>
    </div>
  </div>
  <div>
    <% if current_user.role == "admin" %>
      <div class="nav-item">
        <%= link_to(users_path, class: "nav-link p-6 flex text-gray-600 hover:text-purple-600 truncate #{current_class_by(path: users_path)}") do %>
          <%= heroicon "user-group", options: { class: "h-5 w-5 text-purple-800" } %>
          <span class="px-1">Trainers</span>
        <% end %>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-green-200">
    <%# <main class="container mx-auto mt-28 px-5 flex flex-col	">
      <%= yield %>
    <%# </main> %>
    
    <header class="bg-slate-500 flex justify-between p-4 sticky top-0 h-20 items-center">
      <div>
        logo
      </div>
      <div>
        current_user.email
      </div>
      <div class="md:hidden">
        ☰
      </div>
    </header>
    
    <div class="flex flex-grow">
      <nav class="bg-slate-400 w-1/6 md:flex flex-col hidden justify-between p-4 text-center sticky top-20 h-[calc(100vh-80px)]">
        <div>
          right sidebar TOP
        </div>
        <div>
          <%= button_to "logout", destroy_user_session_path, method: :delete%>
        </div>
      </nav>
      <main class="w-5/6 p-4 bg-rose-300 flex-grow">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/sidebar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-green-200">
    
    <%= render "header" %>
    
    <div class="flex flex-grow">

      <%= render "navbar" %>
      
      <main class="w-5/6 py-10 px-20 bg-[#FFF9FD] flex-grow">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/overview/index.html.erb
<h1 class="text-2xl flex flex-row py-6">
  <%= heroicon "star", options: { class: "h-6 w-6" } %> hey <%=
  current_user.name %>!
</h1>

<% if current_user.recent_pokemons.size > 0%>
<div>Well done! you have new pokemons this week:</div>
  <ul>
    <% current_user.recent_pokemons.each do |pokemon| %>
    <li><%= pokemon.name %></li>
    <% end %>
  </ul>
<% else %>
  <span>You have not caught new pokemons in the last week</span>
<% end %>

app/views/pokemons/_form.html.erb
<%= form_with model: pokemon do |form| %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'w-1/2 text-gradient' %>
    <% pokemon.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :element_type %><br>
    <%= form.select :element_type, options_for_select(Pokemon.element_types.map { |key, value| [key.humanize, key] }), {prompt: "Select Type of Element..."}, class: "form-control" %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.text_field :image, class: 'w-1/2 text-gradient' %>
    <% pokemon.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>



  <div>
    <%= form.label :main_technique %><br>
    <%= form.text_field :main_technique, class: 'w-1/2 text-gradient' %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description, class: 'w-1/2 h-36 text-gradient' %><br>
    <% pokemon.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit class: 'flex flex-row button-add p-3 items-center rounded-2xl text-white' %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1 class="text-2xl">Edit Pokemon</h1>

<%= render "form", pokemon: @pokemon %>

app/views/pokemons/index.html.erb
<div class="">
  <%= form_tag(pokemons_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search], class: 'w-1/2 text-gradient', placeholder: 'Search a pokemon') %>
    <%= submit_tag("Search", class: 'text-gray-400') %>
  <% end %>
</div>

<div class=" py-6 flex flex-row place-content-between">
  <h1 class="text-2xl">Pokemons!</h1>

  <% if current_user.role == "admin" %>
    <div class="flex flex-row button-add p-3 items-center rounded-2xl text-white"> 
      <%= heroicon "plus-circle", options: { class: "h-5 w-5 text-white" } %>
      <%= link_to "Add Pokemon", new_pokemon_path %>
    </div>
  <% end %>
</div>

<div class="relative overflow-x-auto">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead
      class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    >
      <tr>
        <th scope="col" class="px-6 py-3">i</th>
        <th scope="col" class="px-6 py-3">img</th>
        <th scope="col" class="px-6 py-3"><%= link_to "Pokemon Name", :sort => "name"%></th>
        <th scope="col" class="px-6 py-3"><%= link_to "Type", :sort => "element_type"%></th>
      </tr>
    </thead>
    <tbody>
      <% @pokemons.each do |pokemon| %>
      <tr
        class="m-2 bg-white border-b dark:bg-gray-400 dark:border-gray-300 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
        <td class="px-6 py-4"><%= pokemon.id %></td>
        <td class="px-6 py-4"><%= image_tag(pokemon.image, size: "50x50", alt: pokemon.name) %></td>
        <td
          scope="row"
          class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"
        >
          <%= link_to pokemon.name, pokemon %>
        </td>
        <td class="px-6 py-4"><%= pokemon.element_type %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pokemons/new.html.erb
<h1 class="text-2xl">New Pokemon</h1>

<%= render "form", pokemon: @pokemon %>

app/views/pokemons/show.html.erb
<h1 class="text-2xl"><%= @pokemon.name %></h1>



<p>TYPE: <%= @pokemon.element_type %></p>
<p>TECHNIQUE: <%= @pokemon.main_technique %></p>
<p><%= @pokemon.description %></p>

 <% if current_user.role == "admin" %>
  <ul class="flex">
    <li class="flex flex-row w-max button-add p-3 m-3 items-center rounded-2xl text-white"><%= link_to "Edit", edit_pokemon_path(@pokemon) %></li>
    <li class="flex flex-row w-max button-add p-3 m-3 items-center rounded-2xl text-white"><%= link_to "Destroy", pokemon_path(@pokemon), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %></li>
  </ul>
  <% end %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'w-1/2 text-gradient' %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  

  <div>
    <%= form.submit class: 'flex flex-row button-add p-3 items-center rounded-2xl text-white' %>
  </div>
<% end %>

app/views/users/caught_pokemon.html.erb
<%= turbo_frame_tag "caught_pokemon_modal" do %>
  <div aria-labelledby="modal-title"
    aria-modal="true" class="fixed inset-0 z-50 overflow-y-auto bg-black/80" role="dialog">
    <div class="h-screen w-full relative flex items-center justify-center">
      <div class="shadow-xl max-w-2xl bg-white m-1 p-8 prose prose-indigo origin-bottom mx-auto dark:bg-slate-700 dark:text-slate-200 min-w-[600px] rounded-2xl animate-fade-in-up">

        <h1 id="modal-title" class="dark:text-slate-100">Add to your list</h1>

            <div>
                <% @pokemons.all.each do |pokemon| %>
                <li><%= pokemon.name%></li>
                <%= button_to "add pokemon", add_pokemon_path, params: {pokemon_id:
                pokemon.id}, data: { turbo: false }  %> <% end %>
            </div>
            <div>
                <%= link_to "Cancel", my_pokemons_path, class: "bg-slate-100 rounded px-4 py-2 text-center text-slate-700 font-medium hover:bg-slate-200 focus:ring-4 focus:ring-slate-100 no-underline inline-block", data: { turbo: false } %>
            </div>
      </div>
    </div>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<h1 class="text-2xl">Edit Trainee</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<div>
  <%= form_tag(users_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search], class: 'w-1/2 text-gradient', placeholder: 'Search a trainer') %>
    <%= submit_tag("Search", class: 'text-gray-400') %>
  <% end %>
</div>

<div class="py-6 flex flex-row place-content-between">
  <h1 class="text-2xl">Trainees</h1>

  <div class="flex flex-row button-add p-3 items-center rounded-2xl text-white"> 
    <%= heroicon "user-plus", options: { class: "h-5 w-5 text-white" } %>
    <%= link_to "Add Trainee", new_user_path %>
  </div>
</div>


<div class="relative overflow-x-auto">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead
      class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    >
      <tr>
        <th scope="col" class="px-6 py-3">i</th>
        <th scope="col" class="px-6 py-3"><%= link_to "Name", :sort => "name"%></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr
        class="m-2 bg-white border-b dark:bg-gray-400 dark:border-gray-300 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
        <td class="px-6 py-4"><%= user.id %></td>
        <td class="px-6 py-4"><%= link_to user.name, user %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center my-4">
    <div role="navigation" aria-label="Pagination" class="px-3 py-2 mx-2 text-gray-700 no-underline bg-white rounded-lg">
      <div class="flickr_pagination">
        <div class="py-4">
          <%= page_entries_info(@users) %>
        </div>
        <div class="">
          <ul class="pagination flex text-center">
            <li class="disabled"> <%= will_paginate(@users,:previous_label => "&laquo;", :next_label => "&raquo;",:class=>"small-font",:outer_window => 1,:inner_window => 0) %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/my_pokemons.html.erb
<div class="flex flex-row place-content-between">
<h1 class="py-6 text-2xl">My pokemons</h1>

<%= turbo_frame_tag "caught_pokemon_modal" do %>
    <div class="flex flex-row button-add p-3 items-center rounded-2xl text-white"> 
      <%= heroicon "puzzle-piece", options: { class: "h-5 w-5 text-white" } %>
      <%= link_to "Catch it", caught_pokemon_path %>
    </div>
<% end %>

</div>

<div class="relative overflow-x-auto">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead
      class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
    >
      <tr>
        <th scope="col" class="px-6 py-3">Name</th>
        <th scope="col" class="px-6 py-3">Caught Date</th>
        <th scope="col" class="px-6 py-3">Remove</th>
      </tr>
    </thead>
    <tbody>
      <% current_user.pokemons.each do |pokemon| %>
      <tr
        class="m-2 bg-white border-b dark:bg-gray-400 dark:border-gray-300 hover:bg-gray-50 dark:hover:bg-gray-600"
      >
        <td class="px-6 py-4"><%= pokemon.name %></td>
        <td class="px-6 py-4"><%= pokemon.created_at %></td>
        <td class="px-6 py-4">
          <%= button_to "-", remove_pokemon_path, params: {pokemon_id:
          pokemon.id}, data: { turbo_method: :delete, turbo_confirm: "Are you
          sure?" } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1 class="text-2xl">New Trainee</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1 class="text-2xl"><%= @user.name %></h1>


<ul>
  <% @user_pokemons.each do |user_pokemon| %>
      <li>
        <%=  user_pokemon.name%>
      </li>
  <% end %>
</ul>


<ul class="flex">
  <li class="flex flex-row w-max button-add p-3 m-3 items-center rounded-2xl text-white"><%= link_to "Edit", edit_user_path(@user) %></li>
  <li class="flex flex-row w-max button-add p-3 m-3 items-center rounded-2xl text-white"><%= link_to "Destroy", user_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>